version: '3.4'

services:
  avianparkklere.serveruser:
    image: ${DOCKER_REGISTRY-}avianparkklereserveruser
    build:
      context: .
      dockerfile: AvianParkKlere.ServerUser/Dockerfile

  avainparkklere.api:
    image: ${DOCKER_REGISTRY-}avainparkklereapi
    build:
      context: .
      dockerfile: AvainParkKlere.Api/Dockerfile

